name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  PACKAGE_NAME: ACFTCalculator
  XCODEBUILD_WORKSPACE: ACFTCalculator.xcworkspace
  XCODEBUILD_SCHEME: ACFTCalculator
  DEPLOY_DIRECTORY: deploy

jobs:
  test-ios:
    name: Test on iOS ${{ matrix.ios_version }}
    runs-on: macos-11
    strategy:
      matrix:
        ios_version: ["15.0"]
        device_name: ["iPhone 13"]
        xcode_version: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fixes issues with codecov
      - name: Switch Xcode Version
        run: sudo xcode-select -switch "/Applications/Xcode_${{ matrix.xcode_version }}.app"
      - name: Run Tests
        run: sh ./scripts/xcode_build.sh "name=${{ matrix.device_name }},OS=${{ matrix.ios_version }},platform=iOS Simulator"
      - name: Upload Step Output
        uses: actions/upload-artifact@v2
        with:
          name: "tests"
          path: ${{ env.DEPLOY_DIRECTORY }}
  test-macos:
    name: Test on MacOS 11
    runs-on: macos-11
    strategy:
      matrix:
        xcode_version: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fixes issues with codecov
      - name: Switch Xcode Version
        run: sudo xcode-select -switch "/Applications/Xcode_${{ matrix.xcode_version }}.app"
      - name: Run Tests
        run: sh ./scripts/xcode_build.sh "platform=macOS"
      - name: Upload Step Output
        uses: actions/upload-artifact@v2
        with:
          name: "macOS Output"
          path: ${{ env.DEPLOY_DIRECTORY }}
  test-tvos:
    name: Test on tvOS ${{ matrix.tvos_version }}
    runs-on: macos-11
    strategy:
      matrix:
        tvos_version: ["15.0"]
        device_name: ["Apple TV 4K"]
        xcode_version: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fixes issues with codecov
      - name: Switch Xcode Version
        run: sudo xcode-select -switch "/Applications/Xcode_${{ matrix.xcode_version }}.app"
      - name: Run Tests
        run: sh ./scripts/xcode_build.sh "name=${{ matrix.device_name }},OS=${{ matrix.tvos_version }},platform=tvOS Simulator"
      - name: Upload Step Output
        uses: actions/upload-artifact@v2
        with:
          name: "tvOS ${{ matrix.tvos_version }} ${{ matrix.device_name }} Output"
          path: ${{ env.DEPLOY_DIRECTORY }}
  upload-to-codecov:
    needs: [test-ios, test-macos, test-tvos]
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
            directory: tests
