name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  PACKAGE_NAME: ACFTCalculator
  XCODEBUILD_WORKSPACE: ACFTCalculator.xcworkspace
  XCODEBUILD_SCHEME: ACFTCalculator
  DEPLOY_DIRECTORY: deploy

jobs:
  test-ios:
    name: Test on iOS ${{ matrix.ios_version }}
    runs-on: macos-11
    strategy:
      matrix:
        ios_version: ["15.0"]
        device_name: ["iPhone 13"]
        xcode_version: ["13.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Switch Xcode Version
        run: sudo xcode-select -switch "/Applications/Xcode_${{ matrix.xcode_version }}.app"
      - name: Run Tests
        run: sh ./scripts/xcode_build.sh "name=${{ matrix.device_name }},OS=${{ matrix.ios_version }},platform=iOS Simulator"
      - name: Upload Step Output
        uses: actions/upload-artifact@v1
        with:
          name: "iOS ${{ matrix.ios_version }} ${{ matrix.device_name }} Output"
          path: ${{ env.DEPLOY_DIRECTORY }}
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
